<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PWA template</title>

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="pwa/css/bootstrap.min.css">
    <link rel="stylesheet" href="pwa/css/font-awesome.min.css">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div id="worker">
      <div id="print">inicio</div>
      <div class="" id="stop"></div>
      <button type="button" id="startWorker" >startWorker</button>
      <hr>
    </div>
    <div id="localStorage">
      <input type="text" id="localStorageInput" name="" value=""></br>
      <button type="button" name="button" id="setLocalStorage" autofocus>setLocalStorage</button>
      <button type="button" name="button" id="getLocalStorage">getLocalStorage</button></br>
      <input type="text" id="resp_local" name="" value=""></br>
    </div>
<hr>
    <div id="sessionStorage">
      <input type="text" id="sessionStorageInput" name="" value=""></br>
      <button type="button" name="button" id="setSessionStorage">setSessionStorage</button>
      <button type="button" name="button" id="getSessionStorage">getSessionStorage</button></br>
      <input type="text" id="resp_session" name="" value="">
    </div>
  <hr>
  </body>

  <script src="pwa/js/jquery.min.js"></script>
  <script src="pwa/js/bootstrap.min.js"></script>
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->
  <script src="pwa/pwaction/pwaction.js" charset="utf-8"></script>
  <script src="pwa/pwaction/pwaux.js" charset="utf-8"></script>
  <script src="pwa/pwaction/scripts.js" charset="utf-8"></script>
  
</html>
